apiVersion: workspace.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: test-workspace
  namespace: default
spec:
  displayName: "Test Workspace"
  templateRef: "sagemaker-jupyter-template"
  desiredStatus: Running
  storage:
    size: "5Gi"
    mountPath: "/workspace"
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
