apiVersion: v1
kind: Service
metadata:
  name: controller-manager
  namespace: system
spec:
  ports:
  - port: 9443
    targetPort: 9443
    name: webhook
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: jupyter-k8s
