apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jupyter-k8s
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: jupyter-k8s
