apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.namespace }}
  labels:
    app: oauth2-proxy
    component: auth
spec:
  ports:
  - name: http
    port: 4180
    targetPort: http
  selector:
    app: oauth2-proxy
    component: auth