{{- if and .Values.githubRbac.create .Values.githubRbac.createUsersRoles }}
{{- range $user := .Values.githubRbac.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-workspace-binding-{{ $user }}
  namespace: default
  annotations:
    description: "Grants access to workspace.jupyter.org resources for user {{ $user }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-workspace-user-{{ $user }}
subjects:
# For individual user
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ $.Values.dex.oidcUsernamePrefix }}{{ $user }}
{{- end }}
{{- end }}