apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-serviceaccount
  annotations:
    workspace.jupyter.org/service-account-users: |
      - arn:aws:sts::561569208013:assumed-role/DSRole/{{SessionName}}
      - arn:aws:sts::561569208013:assumed-role/DSRole2/specific-user
      - sample-username
    workspace.jupyter.org/service-account-groups: |
      - default-data-scientist