apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth-redirect
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    address: http://oauth2-proxy.{{ .Values.namespace }}:4180
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
      - X-Auth-Request-Id-Token
      - X-Auth-Request-Refresh-Token
      - X-Auth-Request-User
      - X-Auth-Request-Email
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: {{ .Values.namespace }}
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: {{ .Values.domain }}
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---