apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth-redirect
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    address: http://oauth2-proxy.{{ .Values.namespace }}:4180
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
      - X-Auth-Request-Id-Token
      - X-Auth-Request-Refresh-Token
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Groups
      - X-Auth-Request-Preferred-Username
    authRequestHeaders:
      - Cookie
      - X-Forwarded-Uri
      - X-Forwarded-Host
      - X-Forwarded-Proto
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: {{ .Values.namespace }}
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: {{ .Values.domain }}
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
{{- if .Values.authmiddleware.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authmiddleware-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: authmiddleware
    component: auth
spec:
  forwardAuth:
    address: "http://authmiddleware.{{ .Values.namespace }}:8080/auth"
    trustForwardHeader: true
    addAuthCookiesToResponse:
      - "{{ $.Values.authmiddleware.cookieName }}"
      - "{{ .Values.authmiddleware.csrfCookieName }}"
    authRequestHeaders:
      - "Cookie"
      - "X-Forwarded-Uri"
      - "X-Forwarded-Host"
      - "X-Forwarded-Proto"
      - "X-Auth-Request-User"
      - "X-Auth-Request-Email"
      - "X-Auth-Request-Groups"
      - "X-Auth-Request-Preferred-Username"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authmiddleware-verify
  namespace: {{ .Values.namespace }}
  labels:
    app: authmiddleware
    component: auth
spec:
  forwardAuth:
    address: "http://authmiddleware.{{ .Values.namespace }}:8080/verify"
    trustForwardHeader: true
    addAuthCookiesToResponse:
      - "{{ $.Values.authmiddleware.cookieName }}"
      - "{{ .Values.authmiddleware.csrfCookieName }}"
    authRequestHeaders:
      - "Cookie"
      - "X-Forwarded-Uri"
      - "X-Forwarded-Host"
      - "X-Forwarded-Proto"
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: workspace-auth-redirect
  namespace: {{ .Values.namespace }}
  labels:
    app: authmiddleware
    component: auth
spec:
  redirectRegex:
    regex: "^(https?://[^/]+/workspaces/[^/]+/[^/]+)/?$"
    replacement: "${1}/auth"
    permanent: false
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-auth-suffix
  namespace: {{ .Values.namespace }}
  labels:
    app: authmiddleware
    component: auth
spec:
  replacePathRegex:
    regex: "^(/workspaces/[^/]+/[^/]+)/auth$"
    replacement: "$1/"