---
apiVersion: workspaces.jupyter.org/v1alpha1
kind: WorkspaceTemplate
metadata:
  name: restricted-template
spec:
  displayName: "Restricted Data Science Template"
  description: "Template with strict resource and image restrictions"

  # Default image that will be used if no override is provided
  defaultImage: "quay.io/jupyter/datascience-notebook:latest"

  # Restrict which images can be used (whitelist)
  allowedImages:
    - "quay.io/jupyter/datascience-notebook:latest"
    - "quay.io/jupyter/minimal-notebook:latest"

  # Default resource requirements
  defaultResources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  # Strict resource bounds
  resourceBounds:
    cpu:
      min: "250m"
      max: "2"
    memory:
      min: "512Mi"
      max: "4Gi"

  # Storage configuration with limits
  primaryStorage:
    defaultSize: 5Gi
    minSize: 1Gi
    maxSize: 20Gi

---
apiVersion: workspaces.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: test-rejected-workspace
  namespace: default
spec:
  displayName: "Test Rejected Workspace"
  desiredStatus: "Running"

  # Reference the template
  templateRef: "restricted-template"

  # Invalid overrides that violate the template restrictions
  templateOverrides:
    # This image is NOT in the allowed list
    image: "tensorflow/tensorflow:latest-gpu-jupyter"

    # These resources exceed the maximum bounds
    resources:
      requests:
        cpu: "4"      # Exceeds max of 2
        memory: "8Gi" # Exceeds max of 4Gi
      limits:
        cpu: "8"
        memory: "16Gi"

    # Storage size exceeds the maximum
    storageSize: "50Gi"  # Exceeds max of 20Gi

---
apiVersion: workspaces.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: test-valid-workspace
  namespace: default
spec:
  displayName: "Test Valid Workspace"
  desiredStatus: "Running"

  # Reference the template
  templateRef: "restricted-template"

  # Valid overrides within template bounds
  templateOverrides:
    # This image IS in the allowed list
    image: "quay.io/jupyter/minimal-notebook:latest"

    # Minimal resources for testing (K8s best practice for test workloads)
    resources:
      requests:
        cpu: "250m"   # Meets minimum bound (250m to 2) - minimal for testing
        memory: "512Mi" # Within bounds (512Mi to 4Gi) - minimal for testing
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Storage size within bounds
    storageSize: "1Gi"  # Within bounds (1Gi to 20Gi) - minimal for testing