apiVersion: servers.jupyter.org/v1alpha1
kind: WorkspaceTemplate
metadata:
  name: cpu-standard-template
spec:
  displayName: "Standard CPU Workspace"
  description: "General-purpose workspace for data analysis and development"

  # Default image for CPU workspaces
  defaultImage: jupyter/base-notebook:latest

  # Allowed images for standard workloads
  allowedImages:
    - jupyter/base-notebook:latest
    - jupyter/scipy-notebook:latest
    - jupyter/datascience-notebook:latest
    - jupyter/tensorflow-notebook:latest
    - jupyter/minimal-notebook:latest

  # Default resources for CPU workspaces
  defaultResources:
    requests:
      cpu: "0.5"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  # Resource boundaries for overrides
  resourceBounds:
    cpu:
      min: "0.25"
      max: "4"
    memory:
      min: "1Gi"
      max: "8Gi"

  # Storage configuration
  primaryStorage:
    defaultSize: "20Gi"
    minSize: "10Gi"
    maxSize: "100Gi"
    storageClass: "gp3"
    mountPath: "/home/jovyan/work"

  # Allow additional storage volumes
  allowSecondaryStorage: true

  # Environment variables
  environmentVariables:
    - name: JUPYTER_ENABLE_LAB
      value: "yes"
    - name: GRANT_SUDO
      value: "no"

  # Node selector for CPU nodes
  nodeSelector:
    node.kubernetes.io/instance-type: "t3.small"