apiVersion: servers.jupyter.org/v1alpha1
kind: WorkspaceTemplate
metadata:
  name: gpu-datascience-template
spec:
  displayName: "GPU Data Science Workspace"
  description: "High-performance workspace with NVIDIA GPU for ML/AI workloads"

  # Default image with GPU support
  defaultImage: tensorflow/tensorflow:latest-gpu-jupyter

  # Allowed images for GPU workloads
  allowedImages:
    - tensorflow/tensorflow:latest-gpu-jupyter
    - pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
    - nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    - nvcr.io/nvidia/rapidsai/rapidsai:23.06-cuda11.8-runtime-ubuntu22.04-py3.10

  # Default resources for GPU workspaces
  defaultResources:
    requests:
      cpu: "2"
      memory: "8Gi"
      nvidia.com/gpu: "1"
    limits:
      cpu: "4"
      memory: "16Gi"
      nvidia.com/gpu: "1"

  # Resource boundaries for overrides
  resourceBounds:
    cpu:
      min: "1"
      max: "8"
    memory:
      min: "4Gi"
      max: "32Gi"
    gpu:
      min: "1"
      max: "2"

  # Storage configuration
  primaryStorage:
    defaultSize: "50Gi"
    minSize: "20Gi"
    maxSize: "200Gi"
    storageClass: "gp3"
    mountPath: "/home/jovyan/work"

  # Allow additional storage volumes
  allowSecondaryStorage: true

  # Idle shutdown configuration
  idleShutdownConfig:
    enabled: true
    idleTimeout: "2h"
    checkInterval: "10m"

  # Environment variables for GPU
  environmentVariables:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: "compute,utility"
    - name: JUPYTER_ENABLE_LAB
      value: "yes"

  # Node selector for GPU nodes
  nodeSelector:
    node.kubernetes.io/instance-type: "g4dn.xlarge"

  # Tolerations for GPU nodes
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: "true"
      effect: NoSchedule