apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: {{ .Values.namespace }}
  labels:
    app: dex
    component: oauth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5556
    targetPort: http
  selector:
    app: dex
    component: oauth