apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: system
spec:
  dnsNames:
  - jupyter-k8s-controller-manager.jupyter-k8s-system.svc
  - jupyter-k8s-controller-manager.jupyter-k8s-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
