apiVersion: workspaces.jupyter.org/v1alpha1
kind: WorkspaceAccessStrategy
metadata:
  name: aws-ssm-remote-access
  namespace: {{ .Release.Namespace }}
spec:
  displayName: "AWS SSM Remote Access Strategy"
  
  # Controller-specific configuration (not injected into workspace containers)
  controllerConfig:
    SSM_MANAGED_NODE_ROLE: "{{ .Values.remoteAccess.ssmManagedNodeRole }}"
    SSM_SIDECAR_IMAGE: "{{ .Values.remoteAccess.ssmSidecarImage }}"
    AWS_SSM_DOCUMENT_NAME: "{{ .Values.remoteAccess.ssmDocumentName }}"
  
  # Environment variables to merge into workspace containers (if any needed)
  mergeEnv: []

  # Optional: Define access resources if needed in the future
  accessResourceTemplates: []