apiVersion: workspace.jupyter.org/v1alpha1
kind: WorkspaceAccessStrategy
metadata:
  name: aws-ssm-remote-access
  namespace: {{ .Release.Namespace }}
spec:
  displayName: "AWS SSM Remote Access Strategy"
  
  # Controller-specific configuration (not injected into workspace containers)
  controllerConfig:
    SSM_MANAGED_NODE_ROLE: "sagemaker-space-ssm-managed-node-role"
    AWS_SSM_DOCUMENT_NAME: "AWS-StartSSHSession"
  
  # Environment variables to merge into workspace containers (if any needed)
  mergeEnv: []

  # Deployment modifications for SSM remote access
  deploymentSpecModifications:
    podSpec:
      additionalContainers:
        - name: "ssm-agent-sidecar"
          image: {{ .Values.remoteAccess.ssmSidecarImage.containerRegistry }}/{{ .Values.remoteAccess.ssmSidecarImage.repository }}:{{ .Values.remoteAccess.ssmSidecarImage.tag }}
          command: ["/bin/sh"]
          args: 
            - "-c"
            - "cp /usr/local/bin/remote-access-server /opt/amazon/sagemaker/workspace/ || echo \"Failed to copy: $?\"; sleep infinity"
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: "workspace-base"
              mountPath: "/opt/amazon/sagemaker/workspace"
          readinessProbe:
            exec:
              command: ["test", "-f", "/tmp/ssm-registered"]
            initialDelaySeconds: 2
            periodSeconds: 2
      
      volumes:
        - name: "workspace-base"
          emptyDir:
            sizeLimit: "1Gi"

      initContainers:
        - name: workspace-init-container
          image: "{{ .Values.remoteAccess.ssmSidecarImage }}"
          command:
            - /opt/amazon/sagemaker/workspace/bin/entrypoint-workspace-init-container
          volumeMounts:
            - name: workspace-base
              mountPath: /workspace_base_dir
    
    primaryContainer:
      volumeMounts:
        - name: "workspace-base"
          mountPath: "/opt/amazon/sagemaker/workspace"

  # Optional: Define access resources if needed in the future
  accessResourceTemplates: []