apiVersion: workspace.jupyter.org/v1alpha1
kind: WorkspaceAccessStrategy
metadata:
  name: hyperpod-access-strategy
  namespace: {{ .Release.Namespace }}
spec:
  displayName: HyperPod Access Strategy
  {{- if .Values.authMiddleware.enabled }}
  accessResourceNamespace: {{ .Release.Namespace }}
  {{- end }}
  
  {{- if .Values.authMiddleware.enabled }}
  accessResourceTemplates:
    # The authorized route - tries token verification on already authenticated requests
    - kind: IngressRoute
      apiVersion: traefik.io/v1alpha1
      namePrefix: authorized-route
      template: |
        spec:
          entryPoints:
            - web
          routes:
            - match: "Host(`{{ .Values.domain }}`) && PathPrefix(`/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}`)"
              kind: Rule
              priority: 100
              middlewares:
                - name: auth-headers
                  namespace: {{ .Release.Namespace }}
                - name: authmiddleware-verify
                  namespace: {{ .Release.Namespace }}
              services:
                - name: "{{`{{ .Service.Name }}`}}"
                  namespace: "{{`{{ .Service.Namespace }}`}}"
                  port: 8888

    # The unauthorized route - handles bearer-auth path for initial authentication
    - kind: IngressRoute
      apiVersion: traefik.io/v1alpha1
      namePrefix: unauthorized-route
      template: |
        spec:
          entryPoints:
            - web
          routes:
            - match: "Host(`{{ .Values.domain }}`) && PathPrefix(`/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/bearer-auth`)"
              kind: Rule
              priority: 110  # Higher priority specifically for bearer-auth paths
              middlewares:
                - name: auth-headers
                  namespace: {{ .Release.Namespace }}
                - name: authmiddleware-bearer-auth
                  namespace: {{ .Release.Namespace }}
                - name: strip-bearer-auth-suffix
                  namespace: {{ .Release.Namespace }}
              services:
                - name: "{{`{{ .Service.Name }}`}}"
                  namespace: "{{`{{ .Service.Namespace }}`}}"
                  port: 8888
  {{- else }}
  accessResourceTemplates: []
  {{- end }}

  mergeEnv: []

  {{- if .Values.authMiddleware.enabled }}
  accessURLTemplate: "https://{{ .Values.domain }}/workspaces/{{`{{ .Workspace.Namespace }}`}}/{{`{{ .Workspace.Name }}`}}/bearer-auth"
  {{- end }}

  {{- if .Values.remoteAccess.enabled }}
  # Controller-specific configuration (not injected into workspace containers)
  controllerConfig:
    SSM_MANAGED_NODE_ROLE: "sagemaker-space-ssm-managed-node-role"
    AWS_SSM_DOCUMENT_NAME: "AWS-StartSSHSession"

  # Deployment modifications for SSM remote access
  deploymentSpecModifications:
    podSpec:
      additionalContainers:
        - name: "ssm-agent-sidecar"
          image: "{{ .Values.remoteAccess.ssmSidecarImage }}"
          command: ["/bin/sh"]
          args: 
            - "-c"
            - "cp /usr/local/bin/remote-access-server /opt/amazon/sagemaker/workspace/ || echo \"Failed to copy: $?\"; sleep infinity"
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: "workspace-base"
              mountPath: "/opt/amazon/sagemaker/workspace"
          readinessProbe:
            exec:
              command: ["test", "-f", "/tmp/ssm-registered"]
            initialDelaySeconds: 2
            periodSeconds: 2
      
      volumes:
        - name: "workspace-base"
          emptyDir:
            sizeLimit: "1Gi"

      initContainers:
        - name: workspace-init-container
          image: "{{ .Values.remoteAccess.ssmSidecarImage }}"
          command:
            - /opt/amazon/sagemaker/workspace/bin/entrypoint-workspace-init-container
          volumeMounts:
            - name: workspace-base
              mountPath: /workspace_base_dir
    
    primaryContainer:
      volumeMounts:
        - name: "workspace-base"
          mountPath: "/opt/amazon/sagemaker/workspace"
  {{- end }}
