name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      working-directory: '.'

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      working-directory: '.'