name: lint

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync
        working-directory: ${{ inputs.working-directory }}

      - name: Verify ruff check
        run: uv run ruff check
        working-directory: ${{ inputs.working-directory }}

      - name: Verify ruff format has been run
        run: uv run --script scripts/verify_format.py .
        working-directory: ${{ inputs.working-directory }}

      - name: Verify mypy
        run: uv run mypy
        working-directory: ${{ inputs.working-directory }}

  lint-helm:
    name: Helm validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: ./.github/actions/install-helm
      
      - name: Lint Helm chart
        run: helm lint --strict helm/jupyter-k8s
