name: operator-tests
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync
      
      - name: Install Kind
        uses: helm/kind-action@v1.8.0
        with:
          install_only: true
          
      - name: Setup local development environment
        run: make local-dev-setup
        
      - name: Build and deploy operator
        run: make local-deploy
      
      - name: Run operator tests
        run: make operator-tests
        
      - name: Cleanup
        if: always()
        run: make local-dev-teardown