name: Guided Helm

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-chart-aws-traefik-dex:
    name: Chart (AWS Traefik Dex)
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # Do NOT install kind, the target deployment should be an AWS EKS cluster.

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Install kubebuilder
        run: |
          curl -L -o kubebuilder https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.12.0/kubebuilder_linux_amd64
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/
          kubebuilder version

      - name: Generate Helm Chart
        run: make helm-generate

      - name: Lint Helm Chart
        run: make helm-lint

      - name: Run AWS Traefik Dex Helm Tests
        run: make helm-test-aws-traefik-dex