name: unit-tests

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install dependencies
        run: uv sync
        working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        run: uv run pytest
        working-directory: ${{ inputs.working-directory }}